# Generated by Django 5.2 on 2025-04-20 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnerProfile',
            new_name='HouseOwner',
        ),
        migrations.RenameField(
            model_name='houseowner',
            old_name='house_name',
            new_name='boarding_house_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='occupied',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
