# Generated by Django 5.2 on 2025-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_contact_number_tenant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
