# Generated by Django 5.2 on 2025-04-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tenant_guardian_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseowner',
            name='preferred_color',
            field=models.CharField(choices=[('#2E8B57', 'Sea Green'), ('#FF5722', 'Orange'), ('#1E88E5', 'Blue'), ('#FFC107', 'Amber'), ('#6A1B9A', 'Purple'), ('#E91E63', 'Pink'), ('#000000', 'Black'), ('#4CAF50', 'Standard Green')], default='#4CAF50', max_length=7),
        ),
    ]
