# Generated by Django 5.2 on 2025-04-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_houseowner_preferred_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseowner',
            name='preferred_color',
        ),
    ]
