# Generated by Django 5.2 on 2025-05-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tenant_is_active_tenant_moved_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
