# Generated by Django 5.2 on 2025-05-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tenant_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='moved_out_date',
        ),
    ]
