# Generated by Django 5.2 on 2025-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_tenant_is_active_remove_tenant_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseowner',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_profiles/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_profiles/'),
        ),
    ]
